function C = C_jumping_leg(in1,tau,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Oct-2015 09:57:43

y = in1(1,:);
C = y;
