function keypoints = keypoints_jumping_leg(in1,in2)
%KEYPOINTS_JUMPING_LEG
%    KEYPOINTS = KEYPOINTS_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Oct-2015 09:57:42

l = in2(1,:);
th = in1(2,:);
y = in1(1,:);
t2 = sin(th);
keypoints = reshape([0.0,y+l.*t2.*2.0,0.0,l.*cos(th),y+l.*t2,0.0,0.0,y,0.0],[3, 3]);
