function COM = COM_jumping_leg(in1,in2)
%COM_JUMPING_LEG
%    COM = COM_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 12:15:20

c1 = in2(7,:);
c2 = in2(8,:);
dth1 = in1(7,:);
dth2 = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
l1 = in2(9,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
th1 = in1(3,:);
th2 = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th1);
t3 = l1.*t2;
t4 = m1+m2+m3;
t5 = 1.0./t4;
t6 = th1+th2;
t7 = sin(th1);
t8 = l1.*t7;
t9 = sin(t6);
t10 = c2.*t9;
t11 = m1+m2+1.0;
t12 = dx.*t5.*t11;
t13 = cos(t6);
t14 = c2.*t13;
COM = [t5.*(m3+t3+t14+x+m2.*(t3+x+1.0)+m1.*(x+c1.*t2+1.0)+1.0);t5.*(m3+t8+t10+x+y+m1.*(x+y+c1.*t7)+m2.*(t8+x+y));t12-dth1.*t5.*(t8+t10+c1.*m1.*t7+l1.*m2.*t7)-c2.*dth2.*t5.*t9;t12+dy.*t5.*t11+dth1.*t5.*(t3+t14+c1.*m1.*t2+l1.*m2.*t2)+c2.*dth2.*t5.*t13];
