function dC = dC_jumping_leg(in1,tau,in3)
%DC_JUMPING_LEG
%    DC = DC_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 10:41:12

dy = in1(6,:);
dC = dy;
