function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 10:41:10

I1 = in2(4,:);
I2 = in2(5,:);
I3 = in2(6,:);
c1 = in2(7,:);
c2 = in2(8,:);
dth1 = in1(7,:);
dth2 = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
g = in2(11,:);
l1 = in2(9,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
th1 = in1(3,:);
th2 = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = dth1+dth2;
t3 = th1+th2;
t4 = cos(t3);
t11 = cos(th1);
t5 = dx+dy+dth1.*(c2.*t4+l1.*t11)+c2.*dth2.*t4;
t6 = sin(t3);
t9 = sin(th1);
t16 = l1.*t9;
t17 = c2.*t6;
t7 = -dx+dth1.*(t16+t17)+c2.*dth2.*t6;
t8 = dth1.^2;
t10 = dx-c1.*dth1.*t9;
t12 = dx+dy+c1.*dth1.*t11;
t13 = dx.^2;
t14 = dx-dth1.*l1.*t9;
t15 = dx+dy+dth1.*l1.*t11;
E = I1.*t8.*(1.0./2.0)+I2.*t8.*(1.0./2.0)+m2.*(t13+t5.^2+t7.^2).*(1.0./2.0)+m1.*(t13+t10.^2+t12.^2).*(1.0./2.0)+m3.*(t13+t14.^2+t15.^2).*(1.0./2.0)+I3.*t2.^2.*(1.0./2.0)+g.*m3.*(t16+t17+x+y)+g.*m1.*(x+y+c1.*t9)+g.*m2.*(t16+x+y);
