function E = energy_jumping_leg(in1,in2)
%ENERGY_JUMPING_LEG
%    E = ENERGY_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    16-Oct-2015 09:57:41

I1 = in2(7,:);
I2 = in2(8,:);
c1 = in2(2,:);
c2 = in2(3,:);
dth = in1(4,:);
dy = in1(3,:);
g = in2(9,:);
l = in2(1,:);
m1 = in2(4,:);
m2 = in2(5,:);
mh = in2(6,:);
th = in1(2,:);
y = in1(1,:);
t2 = dth.^2;
t6 = cos(th);
t3 = dy+c1.*dth.*t6;
t4 = sin(th);
t9 = c2.*t4;
t10 = l.*t4;
t5 = t9-t10;
t7 = dy+dth.*(c2.*t6+l.*t6);
t8 = dy+dth.*l.*t6.*2.0;
E = I1.*t2.*(1.0./2.0)+I2.*t2.*(1.0./2.0)+m1.*(t3.^2+c1.^2.*t2.*t4.^2).*(1.0./2.0)+mh.*t8.^2.*(1.0./2.0)+m2.*(t2.*t5.^2+t7.^2).*(1.0./2.0)+g.*m1.*(y+c1.*t4)+g.*mh.*(y+l.*t4.*2.0)+g.*m2.*(t9+t10+y);
