function C = C_jumping_leg(in1,tau,in3)
%C_JUMPING_LEG
%    C = C_JUMPING_LEG(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 13:02:50

Y = in1(2,:);
C = Y;
