function COM = COM_jumping_leg(in1,in2)
%COM_JUMPING_LEG
%    COM = COM_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:20

X = in1(1,:);
Y = in1(2,:);
c1 = in2(7,:);
c2 = in2(8,:);
dth1 = in1(7,:);
dth2 = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
l1 = in2(9,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
th1 = in1(3,:);
th2 = in1(4,:);
t2 = cos(th1);
t3 = l1.*t2;
t4 = m1+m2+m3;
t5 = 1.0./t4;
t6 = sin(th1);
t7 = th1+th2;
t8 = l1.*t6;
t9 = sin(t7);
t10 = c2.*t9;
t11 = m1+m2+1.0;
t12 = cos(t7);
t13 = c2.*t12;
COM = [t5.*(X+m3+t3+t13+m1.*(X+c1.*t2)+m2.*(X+t3));t5.*(Y+m3+t8+t10+m1.*(Y+c1.*t6)+m2.*(Y+t8));dx.*t5.*t11-dth1.*t5.*(t8+t10+c1.*m1.*t6+l1.*m2.*t6)-c2.*dth2.*t5.*t9;dy.*t5.*t11+dth1.*t5.*(t3+t13+c1.*m1.*t2+l1.*m2.*t2)+c2.*dth2.*t5.*t12];
