function d_pointC = d_pointC_jumping_leg(in1,in2)
%D_POINTC_JUMPING_LEG
%    D_POINTC = D_POINTC_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:20

dth1 = in1(7,:);
dth2 = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
l1 = in2(9,:);
l2 = in2(10,:);
th1 = in1(3,:);
th2 = in1(4,:);
t2 = th1+th2;
t3 = sin(t2);
t4 = cos(t2);
d_pointC = [dx-dth1.*(l2.*t3+l1.*sin(th1))-dth2.*l2.*t3;dy+dth1.*(l2.*t4+l1.*cos(th1))+dth2.*l2.*t4;0.0];
