function d_pointB = d_pointB_jumping_leg(in1,in2)
%D_POINTB_JUMPING_LEG
%    D_POINTB = D_POINTB_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:19

dth1 = in1(7,:);
dx = in1(5,:);
dy = in1(6,:);
l1 = in2(9,:);
th1 = in1(3,:);
d_pointB = [dx-dth1.*l1.*sin(th1);dy+dth1.*l1.*cos(th1);0.0];
