function keypoints = keypoints_jumping_leg(in1,in2)
%KEYPOINTS_JUMPING_LEG
%    KEYPOINTS = KEYPOINTS_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:18

X = in1(1,:);
Y = in1(2,:);
l1 = in2(9,:);
l2 = in2(10,:);
th1 = in1(3,:);
th2 = in1(4,:);
t2 = cos(th1);
t3 = l1.*t2;
t4 = th1+th2;
t5 = sin(th1);
t6 = l1.*t5;
keypoints = reshape([X,Y,0.0,X+t3,Y+t6,0.0,X+t3+l2.*cos(t4),Y+t6+l2.*sin(t4),0.0],[3,3]);
