function pointB = pointB_jumping_leg(in1,in2)
%POINTB_JUMPING_LEG
%    POINTB = POINTB_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:19

X = in1(1,:);
Y = in1(2,:);
l1 = in2(9,:);
th1 = in1(3,:);
pointB = [X+l1.*cos(th1);Y+l1.*sin(th1);0.0];
