function pointC = pointC_jumping_leg(in1,in2)
%POINTC_JUMPING_LEG
%    POINTC = POINTC_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:19

X = in1(1,:);
Y = in1(2,:);
l1 = in2(9,:);
l2 = in2(10,:);
th1 = in1(3,:);
th2 = in1(4,:);
t2 = th1+th2;
pointC = [X+l2.*cos(t2)+l1.*cos(th1);Y+l2.*sin(t2)+l1.*sin(th1);0.0];
