function pointA = pointA_jumping_leg(in1,in2)
%POINTA_JUMPING_LEG
%    POINTA = POINTA_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    28-Nov-2017 19:12:19

X = in1(1,:);
Y = in1(2,:);
pointA = [X;Y;0.0];
